name: Development Workflow

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  install-deps:
    name: 📦 Install Dependencies
    runs-on: ubuntu-latest
    outputs:
      PNPM_STORE_PATH: ${{ steps.set-pnpm-store-path.outputs.PNPM_STORE_PATH }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '21'

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set pnpm store directory
        id: set-pnpm-store-path
        shell: bash
        run: echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Restore cached app dependencies
        id: cache-app-dependencies-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ steps.set-pnpm-store-path.outputs.PNPM_STORE_PATH }}
            ./node_modules
            ./app.yaml
          key: ${{ runner.os }}-app-dependencies-${{ hashFiles('./pnpm-lock.yaml', './app.yaml') }}
          restore-keys: ${{ runner.os }}-app-dependencies-

      - name: Install Dependencies
        if: steps.cache-app-dependencies-restore.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Cache app dependencies
        if: steps.cache-app-dependencies-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ steps.set-pnpm-store-path.outputs.PNPM_STORE_PATH }}
            ./node_modules
            ./app.yaml
          key: ${{ runner.os }}-app-dependencies-${{ hashFiles('./pnpm-lock.yaml', './app.yaml') }}

  test:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '21'

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/cache/restore@v4
        with:
          path: |
            ${{ needs.install-deps.outputs.PNPM_STORE_PATH }}
            ./node_modules
            ./app.yaml
          key: ${{ runner.os }}-app-dependencies-${{ hashFiles('./pnpm-lock.yaml', './app.yaml') }}
          restore-keys: ${{ runner.os }}-app-dependencies-

      - name: Run sveltkit check
        run: pnpm run check

      - name: Install playwrite broswer list
        run: pnpm exec playwright install

      - name: Run Lint Checks
        run: pnpm run lint

      - name: Run Tests
        run: pnpm run test
